title: Caio Nardelli
description: > # this means to ignore newlines until "baseurl:"
  Caio Nardelli's personal blog with mostly software engineering related content.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.caionardelli.tech" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Caio Nardelli
author-img: caio-nardelli.png # add your photo
about-author: Software Engineer, professional Game Developer
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-devto: caioicy
social-github: caioicy # add your Github handle
social-linkedin: caio-nardelli
social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
